language: c
compiler:
- gcc
- clang
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
install:
- if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.8; fi
before_script:
- if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
- export CTEST_OUTPUT_ON_FAILURE=1
- git submodule update --init --recursive
script:
- cmake samples
- make -j2
